VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Vraagstuk"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public zoekWoord As String
Public vervangMet As String
Public stelVraag As String
Public vraagTitel As String
Public defaultInput As String
Public gevondenRegel As String
Public antwoord As String
Public startPos As Integer
Public eindPos As Integer
Public index As Integer

